### ISSUE TITLE
this library vs angular2-color-picker

### ISSUE THREAD

**Issue by dolanmiu** [zskhan/ng-color-picker#5]
What is the difference between the two libraries? From looking at the source of the two libraries, they seem to be exactly the same:

https://github.com/Alberplz/angular2-color-picker

Here is the diff:

https://www.diffchecker.com/J6AA7E8e

**Comment by zskhan** [comment]
Functionality wise there is no difference but the major issue was compilation and AOT compliance of angular2-color-picker and this issue wasn't resolved since long so i published ng-color-picker which is AOT compliant.
